/** Shared loaders for test data. Plain fs reads, so no bundler is involved. */

import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

import type { PlanetTable } from '../src/planets.js';
import type {
  ConstellationJson,
  StarCatalogJson,
  StarNamesJson,
} from '../src/catalog.js';
import type { DeclinationGridJson } from '../src/declination.js';
import type { DeepSkyJson } from '../src/deepsky.js';

const here = fileURLToPath(new URL('.', import.meta.url));

const read = (path: string): unknown => JSON.parse(readFileSync(join(here, path), 'utf8'));

const data = (name: string): unknown => read(`../../web/public/data/${name}`);

/** All generated by `python tools/build_all.py`. */
export const planetTable = data('planets.json') as PlanetTable;
export const starsJson = data('stars.json') as StarCatalogJson;
export const namesJson = data('names.json') as StarNamesJson;
export const constellationsJson = data('constellations.json') as ConstellationJson;
export const declinationJson = data('declination.json') as DeclinationGridJson;
export const deepSkyJson = data('deepsky.json') as DeepSkyJson;

export interface ReferenceRow {
  utc: string;
  ra: number;
  dec: number;
}

export interface HorizonsFixture {
  site: { name: string; lat: number; lon: number; elevation_km: number };
  epochs: string[];
  geocentric: Record<string, ReferenceRow[]>;
  moonTopocentric: ReferenceRow[];
  moonGeocentric: ReferenceRow[];
}

/** Generated by `python tools/fetch_reference.py`. */
export const horizons = read('./fixtures/horizons.json') as HorizonsFixture;

/** Horizons writes "2026-01-08 19:45"; that is UTC. */
export function parseUtc(stamp: string): Date {
  return new Date(`${stamp.replace(' ', 'T')}:00Z`);
}

/** Degrees to arcseconds, for readable failure messages. */
export const arcseconds = (degrees: number): number => degrees * 3600;
